/*
 Simple DirectMedia Layer
 Copyright (C) 1997-2026 Sam Lantinga <slouken@libsdl.org>

 This software is provided 'as-is', without any express or implied
 warranty.  In no event will the authors be held liable for any damages
 arising from the use of this software.

 Permission is granted to anyone to use this software for any purpose,
 including commercial applications, and to alter it and redistribute it
 freely, subject to the following restrictions:

 1. The origin of this software must not be misrepresented; you must not
 claim that you wrote the original software. If you use this software
 in a product, an acknowledgment in the product documentation would be
 appreciated but is not required.
 2. Altered source versions must be plainly marked as such, and must not be
 misrepresented as being the original software.
 3. This notice may not be removed or altered from any source distribution.
 */

#ifndef SimpleDirectMediaLayer_build_config_h
#define SimpleDirectMediaLayer_build_config_h

#include_next "SDL_build_config.h"

// MARK: - Audio subsystem

#undef SDL_AUDIO_DISABLED
#undef SDL_AUDIO_DRIVER_AAUDIO
#undef SDL_AUDIO_DRIVER_ALSA
#undef SDL_AUDIO_DRIVER_ALSA_DYNAMIC
#undef SDL_AUDIO_DRIVER_COREAUDIO
#undef SDL_AUDIO_DRIVER_DISK
#undef SDL_AUDIO_DRIVER_DOS_SOUNDBLASTER
#undef SDL_AUDIO_DRIVER_DSOUND
#undef SDL_AUDIO_DRIVER_DUMMY
#undef SDL_AUDIO_DRIVER_EMSCRIPTEN
#undef SDL_AUDIO_DRIVER_HAIKU
#undef SDL_AUDIO_DRIVER_JACK
#undef SDL_AUDIO_DRIVER_JACK_DYNAMIC
#undef SDL_AUDIO_DRIVER_N3DS
#undef SDL_AUDIO_DRIVER_NETBSD
#undef SDL_AUDIO_DRIVER_NGAGE
#undef SDL_AUDIO_DRIVER_OHAUDIO
#undef SDL_AUDIO_DRIVER_OPENSLES
#undef SDL_AUDIO_DRIVER_OSS
#undef SDL_AUDIO_DRIVER_PIPEWIRE
#undef SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC
#undef SDL_AUDIO_DRIVER_PRIVATE
#undef SDL_AUDIO_DRIVER_PS2
#undef SDL_AUDIO_DRIVER_PSP
#undef SDL_AUDIO_DRIVER_PULSEAUDIO
#undef SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC
#undef SDL_AUDIO_DRIVER_QNX
#undef SDL_AUDIO_DRIVER_SNDIO
#undef SDL_AUDIO_DRIVER_SNDIO_DYNAMIC
#undef SDL_AUDIO_DRIVER_VITA
#undef SDL_AUDIO_DRIVER_WASAPI

#ifndef SDL_SWIFTPM_AUDIO_ENABLED
#define SDL_AUDIO_DISABLED 1
#endif

#ifdef SDL_SWIFTPM_AUDIO_DRIVER_COREAUDIO_ENABLED
#define SDL_AUDIO_DRIVER_COREAUDIO 1
#endif

#ifdef SDL_SWIFTPM_AUDIO_DRIVER_DISK_ENABLED
#define SDL_AUDIO_DRIVER_DISK 1
#endif

#ifdef SDL_SWIFTPM_AUDIO_DRIVER_DUMMY_ENABLED
#define SDL_AUDIO_DRIVER_DUMMY 1
#endif


// MARK: - Camera subsystem

#undef SDL_CAMERA_DISABLED
#undef SDL_CAMERA_DRIVER_ANDROID
#undef SDL_CAMERA_DRIVER_COREMEDIA
#undef SDL_CAMERA_DRIVER_DUMMY
#undef SDL_CAMERA_DRIVER_EMSCRIPTEN
#undef SDL_CAMERA_DRIVER_MEDIAFOUNDATION
#undef SDL_CAMERA_DRIVER_OPENHARMONY
#undef SDL_CAMERA_DRIVER_PIPEWIRE
#undef SDL_CAMERA_DRIVER_PIPEWIRE_DYNAMIC
#undef SDL_CAMERA_DRIVER_PRIVATE
#undef SDL_CAMERA_DRIVER_V4L2
#undef SDL_CAMERA_DRIVER_VITA

#ifndef SDL_SWIFTPM_CAMERA_ENABLED
#define SDL_CAMERA_DISABLED 1
#endif

#ifdef SDL_SWIFTPM_CAMERA_DRIVER_COREMEDIA_ENABLED
#define SDL_CAMERA_DRIVER_COREMEDIA 1
#endif

#ifdef SDL_SWIFTPM_CAMERA_DRIVER_DUMMY_ENABLED
#define SDL_CAMERA_DRIVER_DUMMY 1
#endif


// MARK: - Dialog subsystem
#undef SDL_DIALOG_DISABLED
#undef SDL_DIALOG_DUMMY

#ifndef SDL_SWIFTPM_DIALOG_ENABLED
#define SDL_DIALOG_DISABLED 1
#endif


// MARK: - Video subsystem
#undef SDL_VIDEO_DISABLED
#undef SDL_VIDEO_DRIVER_ANDROID
#undef SDL_VIDEO_DRIVER_COCOA
#undef SDL_VIDEO_DRIVER_DOSVESA
#undef SDL_VIDEO_DRIVER_DUMMY
#undef SDL_VIDEO_DRIVER_EMSCRIPTEN
#undef SDL_VIDEO_DRIVER_HAIKU
#undef SDL_VIDEO_DRIVER_KMSDRM
#undef SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC
#undef SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM
#undef SDL_VIDEO_DRIVER_N3DS
#undef SDL_VIDEO_DRIVER_NGAGE
#undef SDL_VIDEO_DRIVER_OFFSCREEN
#undef SDL_VIDEO_DRIVER_OPENHARMONY
#undef SDL_VIDEO_DRIVER_OPENVR
#undef SDL_VIDEO_DRIVER_PRIVATE
#undef SDL_VIDEO_DRIVER_PS2
#undef SDL_VIDEO_DRIVER_PSP
#undef SDL_VIDEO_DRIVER_QNX
#undef SDL_VIDEO_DRIVER_RISCOS
#undef SDL_VIDEO_DRIVER_ROCKCHIP
#undef SDL_VIDEO_DRIVER_RPI
#undef SDL_VIDEO_DRIVER_UIKIT
#undef SDL_VIDEO_DRIVER_VITA
#undef SDL_VIDEO_DRIVER_VIVANTE
#undef SDL_VIDEO_DRIVER_VIVANTE_VDK
#undef SDL_VIDEO_DRIVER_WAYLAND
#undef SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC
#undef SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR
#undef SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL
#undef SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR
#undef SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON
#undef SDL_VIDEO_DRIVER_WINDOWS
#undef SDL_VIDEO_DRIVER_X11
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS
#undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XTEST
#undef SDL_VIDEO_DRIVER_X11_HAS_XKBLIB
#undef SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS
#undef SDL_VIDEO_DRIVER_X11_XCURSOR
#undef SDL_VIDEO_DRIVER_X11_XDBE
#undef SDL_VIDEO_DRIVER_X11_XFIXES
#undef SDL_VIDEO_DRIVER_X11_XINPUT2
#undef SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_GESTURE
#undef SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH
#undef SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_SCROLLINFO
#undef SDL_VIDEO_DRIVER_X11_XRANDR
#undef SDL_VIDEO_DRIVER_X11_XSCRNSAVER
#undef SDL_VIDEO_DRIVER_X11_XSHAPE
#undef SDL_VIDEO_DRIVER_X11_XSYNC
#undef SDL_VIDEO_DRIVER_X11_XTEST
#undef SDL_VIDEO_METAL
#undef SDL_VIDEO_OPENGL
#undef SDL_VIDEO_OPENGL_CGL
#undef SDL_VIDEO_OPENGL_EGL
#undef SDL_VIDEO_OPENGL_ES
#undef SDL_VIDEO_OPENGL_ES2
#undef SDL_VIDEO_OPENGL_GLX
#undef SDL_VIDEO_OPENGL_WGL
#undef SDL_VIDEO_STATIC_ANGLE
#undef SDL_VIDEO_VITA_PIB
#undef SDL_VIDEO_VITA_PVR
#undef SDL_VIDEO_VITA_PVR_OGL
#undef SDL_VIDEO_VULKAN

#ifndef SDL_SWIFTPM_VIDEO_ENABLED
#define SDL_VIDEO_DISABLED 1
#endif

#ifdef SDL_SWIFTPM_VIDEO_DRIVER_COCOA_ENABLED
#define SDL_VIDEO_DRIVER_COCOA 1
#endif

#ifdef SDL_SWIFTPM_VIDEO_DRIVER_DUMMY_ENABLED
#define SDL_VIDEO_DRIVER_DUMMY 1
#endif

#ifdef SDL_SWIFTPM_VIDEO_DRIVER_OFFSCREEN_ENABLED
#define SDL_VIDEO_DRIVER_OFFSCREEN 1
#endif

#ifdef SDL_SWIFTPM_VIDEO_OPENGL_ENABLED
#define SDL_VIDEO_OPENGL 1
#ifdef SDL_PLATFORM_MACOS
#define SDL_VIDEO_OPENGL_CGL 1
#endif
#endif

#ifdef SDL_SWIFTPM_VIDEO_OPENGLES_ENABLED
#define SDL_VIDEO_OPENGL_ES2 1
#ifdef SDL_PLATFORM_MACOS
#define SDL_VIDEO_OPENGL_EGL 1
#endif
#endif

#ifdef SDL_SWIFTPM_VIDEO_METAL_ENABLED
#define SDL_VIDEO_METAL 1
#endif

#ifdef SDL_SWIFTPM_VIDEO_VULKAN_ENABLED
#define SDL_VIDEO_VULKAN 1
#endif

#endif /* SimpleDirectMediaLayer_build_config_h */
