// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let excludeList = [
	"android-project",
	"build-scripts",
	"cmake",
	"docs",
	"examples",
	"src/hidapi/testgui",
	"swift",
	"test",
	"VisualC",
	"VisualC-GDK",
	"wayland-protocols",
	"Xcode"
]

let package = Package(
	name: "SimpleDirectMediaLayer",
	platforms: [
		.macOS(.v12)
	],
	products: [
		.library(name: "SimpleDirectMediaLayer", targets: ["SimpleDirectMediaLayer"])
	],
	targets: [
		// The public library
		.target(
			name: "SimpleDirectMediaLayer",
			dependencies: [
				.byNameItem(name: "SDL_Internal_apple", condition: .when(platforms: [.macOS, .iOS, .tvOS, .watchOS, .visionOS])),
				.byNameItem(name: "SDL_Internal_macOS", condition: .when(platforms: [.macOS])),
				.byNameItem(name: "SDL_Internal_posix", condition: .when(platforms: [.macOS, .iOS, .tvOS, .watchOS, .visionOS, .linux, .android])),
			],
			path: ".",
			exclude: excludeList,
			sources: [
				"src/SDL.c",
				"src/SDL_assert.c",
				"src/SDL_error.c",
				"src/SDL_guid.c",
				"src/SDL_hashtable.c",
				"src/SDL_hints.c",
				"src/SDL_log.c",
				"src/SDL_properties.c",
				"src/SDL_utils.c",
				"src/atomic",
				"src/audio/SDL_audio.c",
				"src/audio/SDL_audiocvt.c",
				"src/audio/SDL_audioqueue.c",
				"src/audio/SDL_audioresample.c",
				"src/audio/SDL_audiotypecvt.c",
				"src/audio/SDL_mixer.c",
				"src/audio/disk",
				"src/audio/dummy",
				"src/audio/SDL_wave.c",
				"src/camera/SDL_camera.c",
				"src/camera/dummy",
				"src/core/SDL_core_unsupported.c",
				"src/cpuinfo",
				"src/dialog/SDL_dialog.c",
				"src/dialog/SDL_dialog_utils.c",
				"src/dynapi/SDL_dynapi.c",
				"src/events/SDL_categories.c",
				"src/events/SDL_clipboardevents.c",
				"src/events/SDL_displayevents.c",
				"src/events/SDL_dropevents.c",
				"src/events/SDL_events.c",
				"src/events/SDL_eventwatch.c",
				"src/events/SDL_keyboard.c",
				"src/events/SDL_keymap.c",
				"src/events/SDL_mouse.c",
				"src/events/SDL_notificationevents.c",
				"src/events/SDL_pen.c",
				"src/events/SDL_quit.c",
				"src/events/SDL_touch.c",
				"src/events/SDL_windowevents.c",
				"src/filesystem/SDL_filesystem.c",
				"src/gpu/SDL_gpu.c",
				"src/gpu/vulkan/SDL_gpu_vulkan.c",
				"src/gpu/xr/SDL_openxrdyn.c",
				"src/haptic/SDL_haptic.c",
				"src/haptic/hidapi",
				"src/hidapi/SDL_hidapi.c",
				"src/io/SDL_asyncio.c",
				"src/io/SDL_iostream.c",
				"src/io/generic",
				"src/joystick/SDL_gamepad.c",
				"src/joystick/SDL_joystick.c",
				"src/joystick/SDL_steam_virtual_gamepad.c",
				"src/joystick/controller_type.c",
				"src/joystick/hidapi/SDL_hidapijoystick.c",
				"src/joystick/hidapi/SDL_hidapi_8bitdo.c",
				"src/joystick/hidapi/SDL_hidapi_combined.c",
				"src/joystick/hidapi/SDL_hidapi_flydigi.c",
				"src/joystick/hidapi/SDL_hidapi_gamecube.c",
				"src/joystick/hidapi/SDL_hidapi_gamesir.c",
				"src/joystick/hidapi/SDL_hidapi_gip.c",
				"src/joystick/hidapi/SDL_hidapi_lg4ff.c",
				"src/joystick/hidapi/SDL_hidapi_luna.c",
				"src/joystick/hidapi/SDL_hidapi_ps3.c",
				"src/joystick/hidapi/SDL_hidapi_ps4.c",
				"src/joystick/hidapi/SDL_hidapi_ps5.c",
				"src/joystick/hidapi/SDL_hidapi_rumble.c",
				"src/joystick/hidapi/SDL_hidapi_shield.c",
				"src/joystick/hidapi/SDL_hidapi_sinput.c",
				"src/joystick/hidapi/SDL_hidapi_stadia.c",
				"src/joystick/hidapi/SDL_hidapi_steam.c",
				"src/joystick/hidapi/SDL_hidapi_steam_hori.c",
				"src/joystick/hidapi/SDL_hidapi_steam_triton.c",
				"src/joystick/hidapi/SDL_hidapi_steamdeck.c",
				"src/joystick/hidapi/SDL_hidapi_switch.c",
				"src/joystick/hidapi/SDL_hidapi_switch2.c",
				"src/joystick/hidapi/SDL_hidapi_wii.c",
				"src/joystick/hidapi/SDL_hidapi_xbox360.c",
				"src/joystick/hidapi/SDL_hidapi_xbox360w.c",
				"src/joystick/hidapi/SDL_hidapi_xboxone.c",
				"src/joystick/hidapi/SDL_hidapi_zuiki.c",
				"src/joystick/hidapi/SDL_report_descriptor.c",
				"src/joystick/virtual",
				"src/loadso/dlopen",
				"src/locale/SDL_locale.c",
				"src/main/SDL_main_callbacks.c",
				"src/main/SDL_runapp.c",
				"src/main/generic",
				"src/misc/SDL_url.c",
				"src/notification/SDL_notification.c",
				"src/power/SDL_power.c",
				"src/process/SDL_process.c",
				"src/render/SDL_render.c",
				"src/render/SDL_yuv_sw.c",
				"src/render/gpu/SDL_pipeline_gpu.c",
				"src/render/gpu/SDL_render_gpu.c",
				"src/render/gpu/SDL_shaders_gpu.c",
				"src/render/opengl",
				"src/render/opengles2",
				"src/render/software",
				"src/sensor/SDL_sensor.c",
				"src/sensor/dummy",
				"src/stdlib/SDL_crc16.c",
				"src/stdlib/SDL_crc32.c",
				"src/stdlib/SDL_getenv.c",
				"src/stdlib/SDL_iconv.c",
				"src/stdlib/SDL_malloc.c",
				"src/stdlib/SDL_memcpy.c",
				"src/stdlib/SDL_memmove.c",
				"src/stdlib/SDL_memset.c",
				"src/stdlib/SDL_murmur3.c",
				"src/stdlib/SDL_qsort.c",
				"src/stdlib/SDL_random.c",
				"src/stdlib/SDL_stdlib.c",
				"src/stdlib/SDL_string.c",
				"src/stdlib/SDL_strtokr.c",
				"src/storage/SDL_storage.c",
				"src/storage/generic",
				"src/thread/SDL_thread.c",
				"src/time/SDL_time.c",
				"src/timer/SDL_timer.c",
				"src/tray/SDL_tray_utils.c",
				"src/video/SDL_RLEaccel.c",
				"src/video/SDL_blit.c",
				"src/video/SDL_blit_0.c",
				"src/video/SDL_blit_1.c",
				"src/video/SDL_blit_A.c",
				"src/video/SDL_blit_N.c",
				"src/video/SDL_blit_auto.c",
				"src/video/SDL_blit_copy.c",
				"src/video/SDL_blit_slow.c",
				"src/video/SDL_bmp.c",
				"src/video/SDL_clipboard.c",
				"src/video/SDL_egl.c",
				"src/video/SDL_fillrect.c",
				"src/video/SDL_pixels.c",
				"src/video/SDL_rect.c",
				"src/video/SDL_rotate.c",
				"src/video/SDL_stb.c",
				"src/video/SDL_stretch.c",
				"src/video/SDL_surface.c",
				"src/video/SDL_video.c",
				"src/video/SDL_video_unsupported.c",
				"src/video/SDL_vulkan_utils.c",
				"src/video/SDL_yuv.c",
				"src/video/dummy",
				"src/video/offscreen",
				"src/video/yuv2rgb/yuv_rgb_std.c",
			],
			publicHeadersPath: "include",
			cSettings: [
				.headerSearchPath("include/build_config"),
				.headerSearchPath("src"),
				.headerSearchPath("src/video/khronos"),
				.unsafeFlags(["-fno-modules"])
			],
		),

		// Internal conditionally added targets
		.target(
			name: "SDL_Internal_apple",
			path: ".",
			exclude: excludeList,
			sources: [
				"src/audio/coreaudio",
				"src/camera/coremedia",
				"src/gpu/metal/SDL_gpu_metal.m",
				"src/joystick/apple",
				"src/render/metal/SDL_render_metal.m",
			],
			publicHeadersPath: "swift/SDL_Internal_apple/include",
			cSettings: [
				.headerSearchPath("include"),
				.headerSearchPath("include/build_config"),
				.headerSearchPath("src"),
				.headerSearchPath("src/video/khronos"),
				.unsafeFlags(["-fno-modules"])
			],
		),
		.target(
			name: "SDL_Internal_macOS",
			path: ".",
			exclude: excludeList,
			sources: [
				"src/dialog/cocoa",
				"src/filesystem/cocoa",
				"src/haptic/darwin",
				"src/joystick/darwin",
				"src/locale/macos",
				"src/misc/macos",
				"src/notification/cocoa",
				"src/power/macos",
				"src/tray/cocoa",
				"src/video/cocoa",
			],
			publicHeadersPath: "swift/SDL_Internal_macOS/include",
			cSettings: [
				.headerSearchPath("include"),
				.headerSearchPath("include/build_config"),
				.headerSearchPath("src"),
				.headerSearchPath("src/video/khronos"),
				.unsafeFlags(["-fno-modules"])
			],
			linkerSettings: [
				.linkedFramework("AVFoundation"),
				.linkedFramework("AppKit"),
				.linkedFramework("AudioToolbox"),
				.linkedFramework("Carbon"),
				.linkedFramework("CoreAudio"),
				.linkedFramework("CoreFoundation"),
				.linkedFramework("CoreGraphics"),
				.linkedFramework("CoreHaptics"),
				.linkedFramework("CoreMedia"),
				.linkedFramework("CoreVideo"),
				.linkedFramework("ForceFeedback"),
				.linkedFramework("GameController"),
				.linkedFramework("IOKit"),
				.linkedFramework("Metal"),
				.linkedFramework("QuartzCore"),
				.linkedFramework("Security"),
				.linkedFramework("UniformTypeIdentifiers"),
				.linkedFramework("UserNotifications"),
			],
		),
		.target(
			name: "SDL_Internal_posix",
			path: ".",
			exclude: excludeList,
			sources: [
				"src/filesystem/posix",
				"src/process/posix",
				"src/thread/pthread",
				"src/time/unix",
				"src/timer/unix",
			],
			publicHeadersPath: "swift/SDL_Internal_posix/include",
			cSettings: [
				.headerSearchPath("include"),
				.headerSearchPath("include/build_config"),
				.headerSearchPath("src"),
				.unsafeFlags(["-fno-modules"])
			],
		),


		// MARK: - Example targets

		// examples/demo/01-snake
			.executableTarget(
				name: "examples_demo_01-snake",
				dependencies: [
					"SimpleDirectMediaLayer"
				],
				path: "examples/demo/01-snake",
			),

		// examples/demo/03-woodeneye-008
		.executableTarget(
			name: "examples_demo_02-woodeneye-008",
			dependencies: [
				"SimpleDirectMediaLayer"
			],
			path: "examples/demo/02-woodeneye-008",
		),

		// examples/demo/03-infinite-monkeys
		.executableTarget(
			name: "examples_demo_03-infinite-monkeys",
			dependencies: [
				"SimpleDirectMediaLayer"
			],
			path: "examples/demo/03-infinite-monkeys",
		),

		// examples/demo/04-bytepusher
		.executableTarget(
			name: "examples_demo_04-bytepusher",
			dependencies: [
				"SimpleDirectMediaLayer"
			],
			path: "examples/demo/04-bytepusher",
		),
	]
)

